apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-monitor-deployment
  labels:
    app: cloud-monitor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-monitor
  template:
    metadata:
      labels:
        app: cloud-monitor
    spec:
      containers:
      - name: cloud-monitor
        image: cloud-monitor:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-monitor-service
spec:
  selector:
    app: cloud-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer    